---
title: "Process GWAS Data"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(ADNIMERGE)
library(here)

#ADNI_MERGE processing to get Caucasian ADNI 1 GWAS samples w/imaging data

#First, read in the samples from the .fam plink file to get the FIDs

a2_fam <- read_delim(here("data/ADNI_2_MERGE.fam"), delim = "\t", col_names = FALSE)


#Read in ADNIMERGE data. There will be problems with the tau and abeta columns parsing correctly but we aren't worried about those so its okay if they throw parsing errors for now I should work on parsing those correctly in the future

a2_fdg_patients <- adnimerge %>% 
  filter(ORIGPROT == "ADNI2", 
         PTETHCAT == "Not Hisp/Latino",
         PTRACCAT == "White",
         VISCODE == "bl",
         !is.na(FDG.bl)) %>%
  mutate(PTID = as.character(PTID)) %>% 
  select(PTID)

a2_fam %>% 
  inner_join(a2_fdg_patients, by = c("X2" = "PTID")) %>% 
  select(X1, X2) %>% 
  write_delim(here("data/am2_caucasian_keep_ids_updated.txt"), delim = "\t", col_names = FALSE)

a2_ids <- read_delim(here("data/am2_caucasian_keep_ids.txt"), delim = "\t", col_names = FALSE)
```

## Sex Checking
```{r}
sexcheck <- read.table(here("data/CAUC_sex_checking.sexcheck"), header = TRUE)
plot(sexcheck$F, main = "Sex Distribution", xlab = "Sample", ylab = "F Score") 
```
## Duplicate Checking
```{r}
dups <- read.table(here("data/duplicates.genome"), header = TRUE)

#Relatedness of samples. I might want to exclude these samples
problem_pairs <- dups %>% 
  filter(PI_HAT > 0.4)
  
problem_pairs %>% 
  select(FID1, IID1) %>% 
  filter(!duplicated(IID1)) %>% 
  write_delim(here("data/AD_excluded.txt"), delim = "\t", col_names = FALSE)

#Populations --> PI hat values are much smaller now that populations have been stratified
problem_pairs_small <- dups %>% 
  filter(PI_HAT > 0.05) %>% 
  select(FID1, IID1, FID2, IID2, PI_HAT)
myvars <- c("FID1", "IID1", "FID2", "IID2", "PI_HAT")
problem_pairs[myvars]

## It looks like 2 135_S_4722 and 2 135_S_4723 is the common baddie
```

## Need to make the phenotype table for the FDG pet data